/*
 * Code Written By Eyog Yvon Leonce -FE15P011

 */
package sensorapp.station.ConcreteDisplay;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sensorapp.sensors.NoSensor;
import sensorapp.sensors.Sensor;
import sensorapp.sensors.pojo.Location;
import sensorapp.station.Station;

/**
 *
 * @author leo
 */
public class CreateSensorUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CreateSensorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        SensorName = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        SensorTypeComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        LatitudeSlider = new javax.swing.JSlider();
        LongitudeSlider = new javax.swing.JSlider();
        LongitudetextField = new java.awt.TextField();
        LatitudetextField = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Sensor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SensorName.setText("Enter Name...");
        jScrollPane3.setViewportView(SensorName);

        jLabel1.setText("Sensor Name:");

        jLabel2.setText("Sensor Type:");

        jLabel3.setText("Sensor Longitude:");

        CreateButton.setBackground(new java.awt.Color(102, 102, 255));
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(255, 0, 0));
        CancelButton.setText("Cancel");
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });

        SensorTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEMPERATURE", "PRESSURE", "HUMIDITY", "WIND_VELOCITY" }));
        SensorTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SensorTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Sensor Latitude:");

        LatitudeSlider.setPaintLabels(true);
        LatitudeSlider.setPaintTicks(true);
        LatitudeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LatitudeSliderStateChanged(evt);
            }
        });
        LatitudeSlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LatitudeSliderPropertyChange(evt);
            }
        });

        LongitudeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LongitudeSliderStateChanged(evt);
            }
        });

        LongitudetextField.setText("50");
        LongitudetextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudetextFieldActionPerformed(evt);
            }
        });

        LatitudetextField.setText("50");
        LatitudetextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatitudetextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelButton)
                        .addGap(44, 44, 44)
                        .addComponent(CreateButton)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(SensorTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LatitudeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LongitudeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LongitudetextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(LatitudetextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SensorTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(LongitudeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LongitudetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LatitudeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(LatitudetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void SensorTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SensorTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SensorTypeComboBoxActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        /**
         * Create a sensor and add its value to the corresponding combo list*
         */
        String type;
        Location location = new Location();
        location.setLatitude(LatitudeSlider.getValue());
        location.setLongitude(LongitudeSlider.getValue());
        type = SensorTypeComboBox.getSelectedItem().toString();
        JOptionPane.showMessageDialog(rootPane, ChooseSensorCombobox(type, location));
        ArrayList list = Station.getInstance().getSensorList().getList();


    }//GEN-LAST:event_CreateButtonActionPerformed

    private Sensor ChooseSensorCombobox(String type, Location location) {
        Sensor sensor;
        switch (type) {
            case "HUMIDITY":
                sensor = Station.getInstance().createSensor(SensorName.getText(), type, location);
                StationUI.getInstance().getHumidityComboBox().addItem(SensorName.getText());
                this.dispose();
                return sensor;
            case "TEMPERATURE":
                sensor = Station.getInstance().createSensor(SensorName.getText(), type, location);

                StationUI.getInstance().getTemperatureComboBox().addItem(SensorName.getText());
                this.dispose();
                return sensor;
            case "PRESSURE":
                sensor = Station.getInstance().createSensor(SensorName.getText(), type, location);

                StationUI.getInstance().getPressureComboBox().addItem(SensorName.getText());
                this.dispose();
                return sensor;
            case "WIND_VELOCITY":
                sensor = Station.getInstance().createSensor(SensorName.getText(), type, location);

                StationUI.getInstance().getWindComboBox().addItem(SensorName.getText());
                this.dispose();
                return sensor;
            default:
                sensor = new NoSensor();
                return sensor;
        }
    }

    private void LongitudetextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudetextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudetextFieldActionPerformed

    private void LatitudetextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatitudetextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudetextFieldActionPerformed

    private void LatitudeSliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LatitudeSliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudeSliderPropertyChange

    private void LatitudeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LatitudeSliderStateChanged
        LatitudetextField.setText(Integer.toString(LatitudeSlider.getValue()));
    }//GEN-LAST:event_LatitudeSliderStateChanged

    private void LongitudeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LongitudeSliderStateChanged
        // TODO add your handling code here:
        LongitudetextField.setText(Integer.toString(LongitudeSlider.getValue()));

    }//GEN-LAST:event_LongitudeSliderStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JSlider LatitudeSlider;
    private java.awt.TextField LatitudetextField;
    private javax.swing.JSlider LongitudeSlider;
    private java.awt.TextField LongitudetextField;
    private javax.swing.JTextPane SensorName;
    private javax.swing.JComboBox SensorTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
