/*
 * Code Written By Eyog Yvon Leonce -FE15P011

 */
package sensorapp.station.ConcreteDisplay;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sensorapp.datahelper.DBExecute;
import sensorapp.sensors.Sensor;

/**
 *
 * @author leo
 */
public class SensorSettingsUI extends javax.swing.JFrame {

    
    private Sensor currentSensor;
    /**
     * Creates new form EditSensorUI
     */
    public SensorSettingsUI() {
        initComponents();
        setHideOnClose();
    }

    private void setHideOnClose() {
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SensorNameComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConfrimButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SensorNameTextField = new javax.swing.JTextField();
        SensorLatitudeTextField = new javax.swing.JTextField();
        SensorLongitudeTextField = new javax.swing.JTextField();
        SensorTypeComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        SensorUTimeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SensorNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SensorNameComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Sensor:");

        jLabel2.setText("Sensor Name:");

        jLabel3.setText("Sensor Type:");

        jLabel4.setText("Sensor Latitude:");

        jLabel5.setText("Senosr Longitude:");

        ConfrimButton.setText("Confirm");
        ConfrimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SensorTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEMPERATURE", "PRESSURE", "HUMIDITY", "WIND_VELOCITY" }));
        SensorTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SensorTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Sensor update time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(46, 46, 46)
                .addComponent(ConfrimButton)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(SensorUTimeTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SensorTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SensorNameComboBox, 0, 206, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SensorLatitudeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SensorLongitudeTextField)
                            .addComponent(SensorNameTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SensorNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(SensorTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SensorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SensorLatitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SensorLongitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SensorUTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfrimButton)
                    .addComponent(jButton2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfrimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimButtonActionPerformed
        try {
            // TODO add your handling code here:

            currentSensor.interrupt();
            DBExecute.updateSensorSQL(SensorNameTextField.getText(),currentSensor.getSensor_id(),SensorLongitudeTextField.getText()+","+SensorLatitudeTextField.getText() , Integer.parseInt( SensorUTimeTextField.getText()));
            StationUI.getInstance().clearSensorPannel();
            JOptionPane.showMessageDialog(rootPane, "Updated Sensor!");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SensorSettingsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConfrimButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Clear the names in the name combo box. Then add names in the name combo
     * box if the name is
     *
     * @param evt
     */
    private void SensorTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SensorTypeComboBoxActionPerformed

        SensorNameComboBox.removeAllItems();
        for (int i = 0; i < DBExecute.getSensorList(SensorTypeComboBox.getSelectedItem().toString()).size(); i++) {
            SensorNameComboBox.addItem(DBExecute.getSensorList(SensorTypeComboBox.getSelectedItem().toString()).get(i));

        }

    }//GEN-LAST:event_SensorTypeComboBoxActionPerformed

    private void SensorNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SensorNameComboBoxActionPerformed
        // TODO add your handling code here:
        String sensorName = SensorNameComboBox.getSelectedItem().toString();
        SensorNameTextField.setText(sensorName);

        currentSensor = DBExecute.CreateSensorFromTable(sensorName);
        SensorLatitudeTextField.setText(Double.toString(currentSensor.getLocation().getLatitude()));
        SensorLongitudeTextField.setText(Double.toString(currentSensor.getLocation().getLongitude()));
        SensorUTimeTextField.setText(Integer.toString(currentSensor.getUpdateTime()));
    }//GEN-LAST:event_SensorNameComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfrimButton;
    private javax.swing.JTextField SensorLatitudeTextField;
    private javax.swing.JTextField SensorLongitudeTextField;
    private javax.swing.JComboBox SensorNameComboBox;
    private javax.swing.JTextField SensorNameTextField;
    private javax.swing.JComboBox SensorTypeComboBox;
    private javax.swing.JTextField SensorUTimeTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
