/*
 * Code Written By Eyog Yvon Leonce -FE15P011

 */
package sensorapp.station.ConcreteDisplay;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sensorapp.datahelper.DBExecute;
import sensorapp.sensors.Sensor;
import sensorapp.station.Station;

/**
 *
 * @author leo
 */
public class SensorSettingsUI extends javax.swing.JFrame {

    private Sensor currentSensor = StationUI.getInstance().getCurrentSensor();

    /**
     * Creates new form EditSensorUI
     */
    public SensorSettingsUI() {
        initComponents();
        SensorUTimeTextField.setText(Integer.toString(currentSensor.getUpdateTime()));
        SensorLatitudeTextField.setText(Double.toString(currentSensor.getLocation().getLatitude()));
        SensorLongitudeTextField.setText(Double.toString(currentSensor.getLocation().getLongitude()));
        SensorNameTextField.setText(currentSensor.getSensor_name());

        setHideOnClose();
    }

    private void setHideOnClose() {
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConfrimButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SensorNameTextField = new javax.swing.JTextField();
        SensorLatitudeTextField = new javax.swing.JTextField();
        SensorLongitudeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SensorUTimeTextField = new javax.swing.JTextField();
        RemoveButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Sensor Name:");

        jLabel4.setText("Sensor Latitude:");

        jLabel5.setText("Senosr Longitude:");

        ConfrimButton.setText("Update");
        ConfrimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Sensor update time:");

        RemoveButton1.setBackground(new java.awt.Color(255, 0, 0));
        RemoveButton1.setText("Remove");
        RemoveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RemoveButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(58, 58, 58)
                        .addComponent(ConfrimButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)
                                .addComponent(SensorUTimeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SensorLatitudeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SensorLongitudeTextField)
                                    .addComponent(SensorNameTextField))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SensorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SensorLatitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SensorLongitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SensorUTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfrimButton)
                    .addComponent(jButton2)
                    .addComponent(RemoveButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfrimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimButtonActionPerformed
        try {

            Station.getInstance().stopSensor(currentSensor);

            DBExecute.updateSensorSQL(SensorNameTextField.getText(), currentSensor.getSensor_id(), SensorLongitudeTextField.getText() + "," + SensorLatitudeTextField.getText(), Integer.parseInt(SensorUTimeTextField.getText()));
            StationUI.getInstance().refreshSensorPannel();
            JOptionPane.showMessageDialog(rootPane, "Updated Sensor!");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SensorSettingsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConfrimButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RemoveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButton1ActionPerformed
        try {
            // TODO add your handling code here:
            int i = JOptionPane.showConfirmDialog(rootPane, "Are you sure?");
            System.out.println(i);
            if (i == 0) {
                DBExecute.deleteSensorSQL(currentSensor.getSensor_name());
                StationUI.getInstance().getWindComboBox().removeAllItems();
                StationUI.getInstance().getHumidityComboBox().removeAllItems();
                StationUI.getInstance().getPressureComboBox().removeAllItems();
                StationUI.getInstance().getTemperatureComboBox().removeAllItems();
                StationUI.getInstance().setComboBoxValues();
                StationUI.getInstance().setCurrentSensor(null);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(SensorSettingsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RemoveButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfrimButton;
    private javax.swing.JButton RemoveButton1;
    private javax.swing.JTextField SensorLatitudeTextField;
    private javax.swing.JTextField SensorLongitudeTextField;
    private javax.swing.JTextField SensorNameTextField;
    private javax.swing.JTextField SensorUTimeTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
