/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sensorapp.station.ConcreteDisplay;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import sensorapp.constants.SensorType;
import sensorapp.datahelper.DBExecute;
import sensorapp.station.Station;

/**
 *
 * @author leo
 */
public class StationUI extends javax.swing.JFrame {

    /**
     * Creates new form StationUI
     */
    private Station station;
    private static StationUI instance;

    private StationUI() {
        this.station = Station.getInstance();
        initComponents();

        try {
            setComboBoxValues();
        } catch (SQLException ex) {
            Logger.getLogger(StationUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static StationUI getInstance() {
        if (instance == null) {
            instance = new StationUI();

        }

        return instance;
    }

    public void setComboBoxValues() throws SQLException {
        for (int i = 0; i < DBExecute.getSensors(SensorType.TEMPERATURE.toString()).size(); i++) {
            TemperatureComboBox.addItem(DBExecute.getSensors(SensorType.TEMPERATURE.toString()).get(i));

        }
        for (int i = 0; i < DBExecute.getSensors(SensorType.HUMIDITY.toString()).size(); i++) {
            HumidityComboBox.addItem(DBExecute.getSensors(SensorType.HUMIDITY.toString()).get(i));

        }
        for (int i = 0; i < DBExecute.getSensors(SensorType.PRESSURE.toString()).size(); i++) {
            PressureComboBox.addItem(DBExecute.getSensors(SensorType.PRESSURE.toString()).get(i));

        }
        for (int i = 0; i < DBExecute.getSensors(SensorType.WIND_VELOCITY.toString()).size(); i++) {
            WindComboBox.addItem(DBExecute.getSensors(SensorType.WIND_VELOCITY.toString()).get(i));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        MondayScrollPane = new javax.swing.JScrollPane();
        MondayTable = new javax.swing.JTable();
        TuesdayScrollPane = new javax.swing.JScrollPane();
        TuesdayTable = new javax.swing.JTable();
        WednesdayScrollPane = new javax.swing.JScrollPane();
        WednesdayTable = new javax.swing.JTable();
        ThursdayScrollPane = new javax.swing.JScrollPane();
        ThursdayTable = new javax.swing.JTable();
        FridayScrollPane = new javax.swing.JScrollPane();
        FridayTable = new javax.swing.JTable();
        SaturdayScrollPane = new javax.swing.JScrollPane();
        SaturdayTable = new javax.swing.JTable();
        SundayScrollPane = new javax.swing.JScrollPane();
        SundayTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TemperatureComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        HumidityComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        PressureComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        WindComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        CreateSensor = new javax.swing.JMenuItem();
        Settings = new javax.swing.JMenuItem();
        RemoveSensor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MondayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        MondayScrollPane.setViewportView(MondayTable);

        jTabbedPane3.addTab("Mon", MondayScrollPane);

        TuesdayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        TuesdayScrollPane.setViewportView(TuesdayTable);

        jTabbedPane3.addTab("Tue", TuesdayScrollPane);

        WednesdayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        WednesdayScrollPane.setViewportView(WednesdayTable);

        jTabbedPane3.addTab("Wed", WednesdayScrollPane);

        ThursdayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        ThursdayScrollPane.setViewportView(ThursdayTable);

        jTabbedPane3.addTab("Thu", ThursdayScrollPane);

        FridayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        FridayScrollPane.setViewportView(FridayTable);

        jTabbedPane3.addTab("Fri", FridayScrollPane);

        SaturdayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        SaturdayScrollPane.setViewportView(SaturdayTable);

        jTabbedPane3.addTab("Sat", SaturdayScrollPane);

        SundayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Value"
            }
        ));
        SundayScrollPane.setViewportView(SundayTable);

        jTabbedPane3.addTab("Sun", SundayScrollPane);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("HUIMIDITY SENSORS");

        jLabel1.setText("TEMPERATURE SENSORS");

        jLabel2.setText("PRESSURE SENSORS");

        jLabel4.setText("WIND VELOCITY SENSORS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PressureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(WindComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HumidityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TemperatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TemperatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PressureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HumidityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WindComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Menu.setText("File");

        CreateSensor.setText("Create Sensor");
        CreateSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateSensorActionPerformed(evt);
            }
        });
        Menu.add(CreateSensor);

        Settings.setText("Settings");
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });
        Menu.add(Settings);

        RemoveSensor.setText("Remove Sensor");
        RemoveSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSensorActionPerformed(evt);
            }
        });
        Menu.add(RemoveSensor);

        MenuBar.add(Menu);

        jMenu2.setText("Edit");

        jMenuItem4.setText("Edit Sensor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 194, Short.MAX_VALUE)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsActionPerformed

    private void RemoveSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveSensorActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void CreateSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateSensorActionPerformed
        // TODO add your handling code here:
        CreateSensorUI createSensor = new CreateSensorUI();
        createSensor.setVisible(true);


    }//GEN-LAST:event_CreateSensorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CreateSensor;
    private javax.swing.JScrollPane FridayScrollPane;
    private javax.swing.JTable FridayTable;
    private javax.swing.JComboBox HumidityComboBox;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JScrollPane MondayScrollPane;
    private javax.swing.JTable MondayTable;
    private javax.swing.JComboBox PressureComboBox;
    private javax.swing.JMenuItem RemoveSensor;
    private javax.swing.JScrollPane SaturdayScrollPane;
    private javax.swing.JTable SaturdayTable;
    private javax.swing.JMenuItem Settings;
    private javax.swing.JScrollPane SundayScrollPane;
    private javax.swing.JTable SundayTable;
    private javax.swing.JComboBox TemperatureComboBox;
    private javax.swing.JScrollPane ThursdayScrollPane;
    private javax.swing.JTable ThursdayTable;
    private javax.swing.JScrollPane TuesdayScrollPane;
    private javax.swing.JTable TuesdayTable;
    private javax.swing.JScrollPane WednesdayScrollPane;
    private javax.swing.JTable WednesdayTable;
    private javax.swing.JComboBox WindComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables

    public Station getStation() {
        return station;
    }

    public void setStation(Station station) {
        this.station = station;
    }

    public JMenuItem getCreateSensor() {
        return CreateSensor;
    }

    public void setCreateSensor(JMenuItem CreateSensor) {
        this.CreateSensor = CreateSensor;
    }

    public JScrollPane getFridayScrollPane() {
        return FridayScrollPane;
    }

    public void setFridayScrollPane(JScrollPane FridayScrollPane) {
        this.FridayScrollPane = FridayScrollPane;
    }

    public JTable getFridayTable() {
        return FridayTable;
    }

    public void setFridayTable(JTable FridayTable) {
        this.FridayTable = FridayTable;
    }

    public JComboBox getHumidityComboBox() {
        return HumidityComboBox;
    }

    public void setHumidityComboBox(JComboBox HumidityComboBox) {
        this.HumidityComboBox = HumidityComboBox;
    }

    public JMenu getMenu() {
        return Menu;
    }

    public void setMenu(JMenu Menu) {
        this.Menu = Menu;
    }

  

    public void setMenuBar(JMenuBar MenuBar) {
        this.MenuBar = MenuBar;
    }

    public JScrollPane getMondayScrollPane() {
        return MondayScrollPane;
    }

    public void setMondayScrollPane(JScrollPane MondayScrollPane) {
        this.MondayScrollPane = MondayScrollPane;
    }

    public JTable getMondayTable() {
        return MondayTable;
    }

    public void setMondayTable(JTable MondayTable) {
        this.MondayTable = MondayTable;
    }

    public JComboBox getPressureComboBox() {
        return PressureComboBox;
    }

    public void setPressureComboBox(JComboBox PressureComboBox) {
        this.PressureComboBox = PressureComboBox;
    }

    public JMenuItem getRemoveSensor() {
        return RemoveSensor;
    }

    public void setRemoveSensor(JMenuItem RemoveSensor) {
        this.RemoveSensor = RemoveSensor;
    }

    public JScrollPane getSaturdayScrollPane() {
        return SaturdayScrollPane;
    }

    public void setSaturdayScrollPane(JScrollPane SaturdayScrollPane) {
        this.SaturdayScrollPane = SaturdayScrollPane;
    }

    public JTable getSaturdayTable() {
        return SaturdayTable;
    }

    public void setSaturdayTable(JTable SaturdayTable) {
        this.SaturdayTable = SaturdayTable;
    }

    public JMenuItem getSettings() {
        return Settings;
    }

    public void setSettings(JMenuItem Settings) {
        this.Settings = Settings;
    }

    public JScrollPane getSundayScrollPane() {
        return SundayScrollPane;
    }

    public void setSundayScrollPane(JScrollPane SundayScrollPane) {
        this.SundayScrollPane = SundayScrollPane;
    }

    public JTable getSundayTable() {
        return SundayTable;
    }

    public void setSundayTable(JTable SundayTable) {
        this.SundayTable = SundayTable;
    }

    public JComboBox getTemperatureComboBox() {
        return TemperatureComboBox;
    }

    public void setTemperatureComboBox(JComboBox TemperatureComboBox) {
        this.TemperatureComboBox = TemperatureComboBox;
    }

    public JScrollPane getThursdayScrollPane() {
        return ThursdayScrollPane;
    }

    public void setThursdayScrollPane(JScrollPane ThursdayScrollPane) {
        this.ThursdayScrollPane = ThursdayScrollPane;
    }

    public JTable getThursdayTable() {
        return ThursdayTable;
    }

    public void setThursdayTable(JTable ThursdayTable) {
        this.ThursdayTable = ThursdayTable;
    }

    public JScrollPane getTuesdayScrollPane() {
        return TuesdayScrollPane;
    }

    public void setTuesdayScrollPane(JScrollPane TuesdayScrollPane) {
        this.TuesdayScrollPane = TuesdayScrollPane;
    }

    public JTable getTuesdayTable() {
        return TuesdayTable;
    }

    public void setTuesdayTable(JTable TuesdayTable) {
        this.TuesdayTable = TuesdayTable;
    }

    public JScrollPane getWednesdayScrollPane() {
        return WednesdayScrollPane;
    }

    public void setWednesdayScrollPane(JScrollPane WednesdayScrollPane) {
        this.WednesdayScrollPane = WednesdayScrollPane;
    }

    public JTable getWednesdayTable() {
        return WednesdayTable;
    }

    public void setWednesdayTable(JTable WednesdayTable) {
        this.WednesdayTable = WednesdayTable;
    }

    public JComboBox getWindComboBox() {
        return WindComboBox;
    }

    public void setWindComboBox(JComboBox WindComboBox) {
        this.WindComboBox = WindComboBox;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    public void setjMenuItem4(JMenuItem jMenuItem4) {
        this.jMenuItem4 = jMenuItem4;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JTabbedPane getjTabbedPane3() {
        return jTabbedPane3;
    }

    public void setjTabbedPane3(JTabbedPane jTabbedPane3) {
        this.jTabbedPane3 = jTabbedPane3;
    }
}
